### PR TITLE
Fix a recurring typo

### PR DESCRIPTION
**Pull request by guntbert**
parkig --> parking

### CODE REVIEW

**Comment by vshcherb** [comment]
I guess file names also should be changed

**Comment by guntbert** [comment]
@vshcherb what filenames?

**Comment by vshcherb** [comment]
```
'built-up-areas/built-up_ParkigPermissive',
```
Looks like a file name not a string

**Comment by guntbert** [comment]
thx for catching my blunder :-/
Do you have any idea, whether those referenced files reside in osmand? If not I'd rather change only the text part for now.

**Comment by vshcherb** [comment]
Nope it's only here used in this repo

**Comment by guntbert** [comment]
@vshcherb I think I have found and renamed the correct files.
I have renamed all of them, not only the ones mentioned in my first commit.

**Pull request merged**
