### PR TITLE
Update brouter.md

### PR DESCRIPTION
**Pull request by myfta**
Improved and expanded existing text for clarity.

### CODE REVIEW

**Comment by myfta** [comment]
PS. If someone can explain where to upload it to, I can add a new profile image (in English)!
brouter_profile

**Comment by myfta** [comment]
@EugeneZmeuk I still don't see the update on the webpage. (I have deleted the cached files!)

Could you update the image or point me to how and where to do it. Thanks.

**Comment by EugeneZmeuk** [comment]
> @EugeneZmeuk I still don't see the update on the webpage. (I have deleted the cached files!)
> 
> Could you update the image or point me to how and where to do it. Thanks.

I have updated the web

**Comment by myfta** [comment]
> > @EugeneZmeuk I still don't see the update on the webpage. (I have deleted the cached files!)
> > Could you update the image or point me to how and where to do it. Thanks.
> 
> I have updated the web

That's better. Thanks.

Can we sort the image too, please.

**Comment by EugeneZmeuk** [comment]
> > > @EugeneZmeuk I still don't see the update on the webpage. (I have deleted the cached files!)
> > > Could you update the image or point me to how and where to do it. Thanks.
> > 
> > 
> > I have updated the web
> 
> That's better. Thanks.
> 
> Can we sort the image too, please.

done

**Pull request merged**
