### PR TITLE
Upgrade the repository to yarn v3, pnp enabled

### PR DESCRIPTION
**Pull request by tiziodcaio**
Hello, due to is compatible I greatly suggest to do this update to enable pnp. For information [here](https://yarnpkg.com/getting-started/qa)

### CODE REVIEW

**Comment by vshcherb** [comment]
Hello, Thank for your request. I added 1 dependency before I saw it. Could you please help to explain how did you do it to resolve conflicts and how pnp going to make project different.

**Comment by tiziodcaio** [comment]
Using pnp let you to not use the node modules folder; instead zipped versions of all the node dependencies are automatically loaded. Now I will add the dependency change...

**Comment by vshcherb** [comment]
```
[ERROR] The image at /var/lib/jenkins/workspace/UpdateWebFrontend/main/blog/2019-03-23-story-2/story-2-4.jpg can't be read correctly. Please ensure it's a valid image.
The "path" argument must be of type string. Received type number (36)

+ yarn run build
Creating an optimized production build...
Failed to compile.

Failed to load config "react-app" to extend from.
Referenced from: /var/lib/jenkins/workspace/UpdateWebFrontend/map/package.json

```

**Comment by tiziodcaio** [comment]
So... Maybe can I upgrade without enabling pnp?

**Comment by tiziodcaio** [comment]
This type of error usually is due to pnp... Now works?

**Pull request merged**
